<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please Sign In</h3>
                </div>
                <div class="panel-body">
                    <?php $form = $this->getForm(); ?>
                    <?php $form->start(); ?>
                    <fieldset>
                        <div class="form-group">
                            <label>ログインID</label>
                            <?php echo $form->adminLogin->login, $form->adminLogin->login->error; ?>
                        </div>
                        <div class="form-group">
                            <label>パスワード</label>
                            <?php echo $form->adminLogin->password, $form->adminLogin->password->error; ?>
                        </div>
                        <div class="checkbox">
                            <?php echo $form->adminLogin->remeber, $form->adminLogin->remeber->error; ?>
                        </div>
                        <!-- Change this to a button or input when using this as a form -->
                        <!--<a href="index.html" class="btn btn-lg btn-success btn-block">Login</a>-->
                        <?php echo $form->submit; ?>
                    </fieldset>
                    <?php $form->end(); ?>
                </div>
            </div>
        </div>
    </div>
</div>
