<?php
$adminUser = $this->getModel();
?>
<nav class="navbar navbar-default navbar-static-top m-b-0">
    <div class="navbar-header">
        <div class="top-left-part">
            <a class="logo" href="/admin/index">
                <b><i class="mdi mdi-access-point fa-fw"></i> </b>
                <span class="hidden-xs">Cngo</span>
            </a>
        </div>
        <!-- /Logo -->
        <!-- Search input and Toggle icon -->
        <ul class="nav navbar-top-links navbar-right pull-right">
            <li>
                <form role="search" class="app-search hidden-sm hidden-xs m-r-10">
                    <input type="text" placeholder="Search..." class="form-control"> <a href=""><i class="fa fa-search"></i></a>
                </form>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#">
                    <img src="<?=$adminUser->getAvatar(); ?>" alt="user-img" width="36" class="img-circle">
                    <b class="hidden-xs"><?=$adminUser->getName(); ?> </b>
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu dropdown-user animated flipInY">
                    <li>
                        <div class="dw-user-box">
                            <div class="u-img">
                                <img src="<?=$adminUser->getAvatar(); ?>" alt="user" />
                            </div>
                            <div class="u-text">
                                <h4><?=$adminUser->getName(); ?> </h4>
                                <p class="text-muted"><?=$adminUser->getEmail(); ?></p>
                                <a href="<?=$adminUser->getProfileEditUrl(); ?>" class="btn btn-rounded btn-danger btn-sm">View Profile</a>
                            </div>
                        </div>
                    </li>
                    <!-- <li role="separator" class="divider"></li> -->
                    <!-- <li><a href="<?=$adminUser->getProfileEditUrl(); ?>"><i class="fa fa-gear fa-fw"></i> Edit Profile</a></li> -->
                    <!-- <li><a href="#"><i class="ti-wallet"></i> My Balance</a></li>
                    <li><a href="#"><i class="ti-email"></i> Inbox</a></li> -->
                    <li role="separator" class="divider"></li>
                    <li><a href="#"><i class="ti-settings"></i> Account Setting</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="/admin/logout"><i class="fa fa-sign-out"></i> Logout</a></li>
                </ul>
                <!-- /.dropdown-user -->
            </li>

            <!-- /.dropdown -->
        </ul>
    </div>
    <!-- /.navbar-header -->
    <!-- /.navbar-top-links -->
    <!-- /.navbar-static-side -->
</nav>

<?= $this->getContainer('Side'); ?>
