<div class="navbar-default sidebar" role="navigation">
<div class="sidebar-nav">
    <div class="sidebar-head">
        <h3><span class="fa-fw open-close"><i class="ti-menu hidden-xs"></i><i class="ti-close visible-xs"></i></span> <span class="hide-menu">Navigation</span></h3> </div>
    <ul class="nav" id="side-menu">
        <?php foreach ($this->getData() as $data) : ?>
        <li>
            <a href="<?= $data['link'] ?? '#' ?>">
            <?= $data['icon'] ?? '' ?> <span class="hide-menu"><?= $data['title'] ?></span>
            <?php if (!empty($data['child'])): ?><span class="fa arrow"></span><?php endif; ?>
            </a>
            <?php if (!empty($data['child'])) : ?>
            <ul class="nav nav-second-level">
            <?php foreach ($data['child'] as $item) : ?>
            <li>
                <a href="<?= $item['link'] ?? '#' ?>">
                <?= $item['icon'] ?? '' ?> <span class="hide-menu"><?= $item['title'] ?></span>
            <?php if (!empty($item['child'])): ?><span class="fa arrow"></span><?php endif; ?>
            </a>
            <?php if (!empty($item['child'])) : ?>
            <ul class="nav nav-third-level">
            <?php foreach ($item['child'] as $row) : ?>
            <li>
                <a href="<?= $row['link'] ?? '#' ?>">
                <?= $row['icon'] ?? '' ?> <?= $row['title'] ?>
                </a>
            </li>
            <?php endforeach; ?>
            </ul>
            <?php endif; ?>
            </li>
            <?php endforeach; ?>
            </ul>
            <?php endif; ?>
        </li>
        <?php endforeach; ?>
    </ul>
</div>
</div>
