                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-clock-o fa-fw"></i> Responsive Timeline
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <ul class="timeline">
				<?php foreach ($timeline as $index => $row) { ?>
                                <li<?php if ($index % 2) { ?> class="timeline-inverted"<?php } ?>>
                                    <?php if (!empty($row['icon'])) { ?><div class="timeline-badge info"><i class="fa <?php echo $row['icon'] ?>"></i></div><?php } ?>                                    
                                    <div class="timeline-panel">
                                        <div class="timeline-heading">
                                          <h4 class="timeline-title"><?php echo $row['title'] ?></h4>
					  <?php if (isset($row['datetime'])) { ?>
					  <p><small class="text-muted"><i class="fa fa-clock-o"></i><?php echo $row['datetime'] ?></small></p>
					  <?php } ?>
                                        </div>
                                        <div class="timeline-body">
					  <?php echo $row['body']; ?>
					  <?php if (isset($row['action'])) { ?>
                                            <hr>
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown">
                                                    <i class="fa fa-gear"></i>  <span class="caret"></span>
                                                </button>
                                                <ul class="dropdown-menu" role="menu">
						  <?php foreach ($row['action'] as $index => $actionGroup) { ?>
						  <?php if ($index > 0) { ?><li class="divider"></li><?php } ?>
						  <?php foreach ($actionGroup as $act) { ?>
                                                  <li><a href="<?php echo $act['href'] ?>"><?php echo $act['title'] ?></a></li>
						  <?php } ?>
						  <?php } ?>
                                                </ul>
                                            </div>
					    <?php } ?>
                                        </div>
                                    </div>
                                </li>
				<?php } ?>
                            </ul>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
