<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" type="image/png" sizes="16x16" href="../plugins/images/favicon.png">
<title><?= $title ?></title>
<?php $css = $self->getStyle(); ?>
<?php foreach ($css as $link) { ?>
  <link href="<?= $link; ?>" rel="stylesheet">
<?php } ?>
</head>
<body>
<!-- Preloader -->
<div class="preloader">
  <div class="cssload-speeding-wheel"></div>
</div>
<section id="wrapper" class="new-login-register">
    <?= $self->getContainer('Main'); ?>
</section>
<!-- jQuery -->
<?php $scripts = $self->getScript(); ?>
<?php foreach ($scripts as $link) { ?>
  <script src="<?= $link ?>"></script>
<?php } ?>
</body>
</html>
