<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" type="image/png" sizes="16x16" href="../plugins/images/favicon.png">
<title>{{ title }}</title>
{% for link in self.style %}
  <link href="{{ link }}" rel="stylesheet">
{% endfor %}
</head>
<body>
<!-- Preloader -->
<div class="preloader">
  <div class="cssload-speeding-wheel"></div>
</div>
<section id="wrapper" class="new-login-register">
  {{ self.containers.Main.content | raw }}
</section>
<!-- jQuery -->
{% for link in self.script %}
<script src="{{ link }}"></script>
{% endfor %}
</body>
</html>
