<?php
use Framework\Module\Cngo\Admin\Controller\Users\RegisterController;
use Framework\Module\Cngo\Admin\Controller\Users\EditController;
use Framework\Module\Cngo\Admin\Controller\Users\DeleteController;
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?=$title?></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <!-- /.panel-heading -->
            <div class="panel-body">
                <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>ログインID</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->getData('adminUsers') as $index => $adminUser) : ?>
                            <tr class="<?= $index % 2 ? 'even' : 'odd' ?>">
                                <td><?=$adminUser['adminUsersId']; ?></td>
                                <td><?=$adminUser['login']; ?></td>
                                <td class="center">
                                    <a href="<?=$this->getRouter()->linkto(EditController::class, $adminUser['adminUsersId']); ?>" class="btn btn-primary">編集</a>
                                    <a href="<?=$this->getRouter()->linkto(DeleteController::class, $adminUser['adminUsersId']); ?>" class="btn btn-danger">削除</a>
                                </td>
                            </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>
                <a href="<?=$this->getRouter()->linkto(RegisterController::class, $adminUser['adminUsersId']); ?>" class="btn btn-danger">新しい管理者を追加</a>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<?php 
    $this->getLayout()->registerScript('/dataTables.responsive.js/jquery.dataTables.min.js');
    $this->getLayout()->registerScript('/dataTables.responsive.js/dataTables.bootstrap.min.js');
    $this->getLayout()->registerScript('/dataTables.responsive.js/dataTables.responsive.js');
 ?>
<script>
$(function() {
    $('#dataTables-example').DataTable({
        responsive: true
    });
});
</script>
