    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><?=$title?></h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <?php $form = $this->getForm(); ?>
                    <?php $form->start(); ?>
                    <fieldset>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>ログインID</label>
                                    <?php echo $form->login, $form->login->error; ?>
                                </div>
                                <div class="form-group">
                                    <label>パスワード</label>
                                    <?php echo $form->password, $form->password->error; ?>
                                </div>
                                <div class="form-group">
                                    <label>パスワード確認</label>
                                    <?php echo $form->passwordConfirm, $form->passwordConfirm->error; ?>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <?php echo $form->submit; ?>
                            </div>
                        </div>
                    </fieldset>
                    <?php $form->end(); ?>
                </div>
            </div>
        </div>
    </div>
