
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon.png">
<title><?= $title ?></title>

<?php $css = $this->getStyle(); ?>
<?php foreach ($css as $link) { ?>
    <link href="<?= $link; ?>" rel="stylesheet">
<?php } ?>
</head>
<body>
<div id="wrapper">
    <?= $this->getContainer('Header'); ?>

    <div class="container-fluid">
        <?= $this->getContainer('Main'); ?>
    </div>
</div>
<?php $scripts = $this->getScript(); ?>
<?php foreach ($scripts as $link) { ?>
    <script src="<?= $link ?>"></script>
<?php } ?>
</body>
</html>