<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" sizes="16x16" href="../plugins/images/favicon.png">
    <title>{{ title }}</title>
    {% for link in self.style %}
      <link href="{{ link }}" rel="stylesheet">
    {% endfor %}
</head>

<body class="fix-header">
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
        </svg>
    </div>

    <div id="wrapper">
    {{ self.containers.Header | raw }}
    <div id="page-wrapper">
            <div class="container-fluid">
            {{ self.containers.Main | raw }}
            </div>

        </div>
    </div>

    {% for link in self.script %}
    <script src="{{ link }}"></script>
    {% endfor %}
        <script type="text/javascript">
        (function () {
                [].slice.call(document.querySelectorAll('.sttabs')).forEach(function (el) {
                new CBPFWTabs(el);
            });
        })();
    </script>
</body>

</html>