<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?php echo $title ?></title>

    <?php $css = $this->getStyle(); ?>
    <?php foreach ($css as $link) { ?>
    <link href="<?php echo $link; ?>" rel="stylesheet">
    <?php } ?>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAQptvnuOlYj4GVoG_Ao0fozZHpc7mYklg&libraries=places&language=ja"></script>
</head>

  <body>

    <div id="wrapper">
        <?php echo $this->getContainer('Main'); ?>
    </div>
    <?php $scripts = $this->getScript(); ?>
    <?php foreach ($scripts as $link) { ?>
    <script src="<?php echo $link ?>"></script>
    <?php } ?>
  </body>

</html>
