<?php
$controller = $this->getData()['controller'];
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?=$title?></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>ID</label>
                            <label class="form_label form_text"><?=$controller['controllerId'] ?></label>
                        </div>
                    </div>
                </div>
                <?php $form = $this->getForm(); ?>
                <?php $form->start(); ?>
                    <div class="row">
                        <div class="col-md-12">
                            <?= $form->submit; ?>
                        </div>
                    </div>
                </fieldset>
                <?php $form->end(); ?>
            </div>
        </div>
    </div>
</div>
