    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><?=$title?></h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <?php $form = $this->getForm(); ?>
                    <?php $form->start(); ?>
                    <fieldset>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>カラム</label>
                                    <?= $form->{entity}->column, $form->{entity}->column->error; ?>
                                </div>
                            </div>
                            <?=$this->getContainer('SubForm')->getContent(); ?>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <?= $form->submit; ?>
                            </div>
                        </div>
                    </fieldset>
                    <?php $form->end(); ?>
                </div>
            </div>
        </div>
    </div>
