<div class="lg-info-panel">
<div class="inner-panel">
    <a href="javascript:void(0)" class="p-20 di"><img src="/asset/material/plugins/images/admin-logo.png"></a>
    <div class="lg-content">
        <h2> 管理画面ログイン画面</h2>
        <p class="text-muted">　ここで、自社サービスの紹介などを置く </p>
    </div>
</div>
</div>
<div class="new-login-box">
  <div class="white-box">
      <h3 class="box-title m-b-0">Sign In to Admin</h3>
      <small>Enter your details below</small>
      <?php $form = $this->getForm(); ?>
      <?php $form->start(); ?>

      <div class="form-group  m-t-20">
        <div class="col-xs-12">
            <label>ログインID</label>
            <?= $form->adminLogin->login, $form->adminLogin->login->error; ?>
        </div>
      </div>
      <div class="form-group">
        <div class="col-xs-12">
            <label>パスワード</label>
            <?= $form->adminLogin->password, $form->adminLogin->password->error; ?>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-12">
        <div class="checkbox checkbox-info pull-left p-t-0 col-md-6">
            <input id="checkbox-signup" type="checkbox">
            <label for="checkbox-signup"> Remember me </label>
        </div>
        <div class="col-md-6">
            <a href="javascript:void(0)" id="to-recover" class="text-dark pull-right"><i class="fa fa-lock m-r-5"></i> Forgot pwd?</a> </div>
        </div>
      </div>
      <div class="form-group text-center m-t-20">
        <div class="col-xs-12">
          <button class="btn btn-info btn-lg btn-block btn-rounded text-uppercase waves-effect waves-light" type="submit">Log In</button>
        </div>
      </div>
      <?php $form->end(); ?>
    <form class="form-horizontal" id="recoverform" action="index.html">
      <div class="form-group ">
        <div class="col-xs-12">
          <h3>Recover Password</h3>
          <p class="text-muted">Enter your Email and instructions will be sent to you! </p>
        </div>
      </div>
      <div class="form-group ">
        <div class="col-xs-12">
          <input class="form-control" type="text" required="" placeholder="Email">
        </div>
      </div>
      <div class="form-group text-center m-t-20">
        <div class="col-xs-12">
          <button class="btn btn-primary btn-lg btn-block text-uppercase waves-effect waves-light" type="submit">Reset</button>
        </div>
      </div>
      </form>
      </div>
</div>
