<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Template</h3>
                </div>
                <div class="panel-body">
                    <?php
declare(strict_types=1); $form = $this->getForm(); ?>
                    <?php
declare(strict_types=1); $form->start(); ?>
                    <fieldset>
                        <div class="form-group">
                            <label>Field</label>
                            <?= $form->form->field, $form->form->field->error; ?>
                        </div>
                        <?= $form->submit; ?>
                    </fieldset>
                    <?php
declare(strict_types=1); $form->end(); ?>
                </div>
            </div>
        </div>
    </div>
</div>
