<?php
use Framework\Module\Cms\Admin\Controller\Blog\RegisterController;
use Framework\Module\Cms\Admin\Controller\Blog\EditController;
use Framework\Module\Cms\Admin\Controller\Blog\DeleteController;
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?=$title?></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <a href="<?=$this->getRouter()->linkto(RegisterController::class); ?>" class="btn btn-danger">追加[博客]</a>
        <p></p>
    </div>
    <div class="col-lg-12">
        <div class="panel panel-default">
            <!-- /.panel-heading -->
            <div class="panel-body">
                <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <thead>
                        <tr>
                            <th>ID</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->getData('blog') as $index => $blog) : ?>
                            <tr class="<?= $index % 2 ? 'even' : 'odd' ?>">
                                <td><?=$blog['blogId']; ?></td>
                                <td class="center">
                                    <a href="<?=$this->getRouter()->linkto(EditController::class, $blog['blogId']); ?>" class="btn btn-primary">編集</a>
                                    <a href="<?=$this->getRouter()->linkto(DeleteController::class, $blog['blogId']); ?>" class="btn btn-danger">削除</a>
                                </td>
                            </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<?php
    $this->getLayout()->registerScript('/../js/dataTables/jquery.dataTables.min.js');
    $this->getLayout()->registerScript('/../js/dataTables/dataTables.bootstrap.min.js');
    $this->getLayout()->registerScript('/../js/dataTables/dataTables.responsive.js');
 ?>
<script>
// $(function() {
//     $('#dataTables-example').DataTable({
//         responsive: true
//     });
// });
</script>
