    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><?=$title?></h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <?php $form = $this->getForm(); ?>
                    <?php $form->start(); ?>
                    <fieldset>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>ログインID</label>
                                    <?= $form->adminUser->login, $form->adminUser->login->error; ?>
                                </div>
                                <div class="form-group">
                                    <label>管理者名</label>
                                    <?= $form->adminUser->name, $form->adminUser->name->error; ?>
                                </div>
                                <div class="form-group">
                                    <label>メールアドレス</label>
                                    <?= $form->adminUser->email, $form->adminUser->email->error; ?>
                                </div>
                                <div class="form-group">
                                    <label>パスワード</label>
                                    <?= $form->adminUser->password, $form->adminUser->password->error; ?>
                                </div>
                                <div class="form-group">
                                    <label>パスワード確認</label>
                                    <?= $form->adminUser->passwordConfirm, $form->adminUser->passwordConfirm->error; ?>
                                </div>
                            </div>
                            <?=$this->getContainer('Form'); ?>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <?= $form->submit; ?>
                            </div>
                        </div>
                    </fieldset>
                    <?php $form->end(); ?>
                </div>
            </div>
        </div>
    </div>
